### ISSUE TITLE
How can I calibrate the compass?

### ISSUE THREAD

**Issue by alireza3137** [ibrahimcahit/MPU9255-Quaternion-AHRS-STM32#1]
Many thanks for sharing your great job.
I was wondering how can I calibrate compass? What do you mean about wave in 8 figure? In what plan should I do this job?

**Comment by ibrahimcahit** [comment]
Make sensor faicng upwards and just wave 8 like this:

https://www.youtube.com/watch?v=J_cZnPcW-Yw

I mean, like calibrating your phones compass.

**Comment by alireza3137** [comment]
hi thanks for your reply. 
I port your code but yaw axis is crazy. when I rotate the mpu9250 about Z axis the yaw did not follow my movement. 

How can I solve it?

**Comment by ibrahimcahit** [comment]
- Which board/MCU did you use. (STM32F103, F3, etc...)
- Did you calibrate the compass?
- Can you share a video about it?
And, are you using MPU9250 or 9255?

**Comment by alireza3137** [comment]
I use stm32f407ZG.
yes I have calibrated the compass as mentioned video you send it here.
I am using MPU9250.

**Comment by alireza3137** [comment]
Any suggestion?
